name: Deply to TEST env.

on:
  push:
    branches: [ test ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:

    - name: Acquire source code
      uses: actions/checkout@v2
    
    - name: Setup AWS login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Perform AWS login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Dockerize and push to AWS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: warehouse-backend-test
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG --build-arg aws_bin_test=${{ secrets.AWS_SECRETS_BIN_TEST }} --build-arg aws_bin_prod=${{ secrets.AWS_SECRETS_BIN_PROD }} --build-arg aws_key_test=${{ secrets.AWS_SECRETS_KEY_TEST }} --build-arg aws_key_prod=${{ secrets.AWS_SECRETS_KEY_PROD }} --build-arg aws_secret_test=${{ secrets.AWS_SECRETS_SECRET_TEST }} --build-arg aws_secret_prod=${{ secrets.AWS_SECRETS_SECRET_PROD }} .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 

    - name: Prepare deploy script
      run: |
        curl -O https://raw.githubusercontent.com/andersondomingues/warehouse-backend/test/scripts/Dockerrun.aws.json-test
        zip -r script.zip Dockerrun.aws.json-test

    - name: Deploy to beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_EBS }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EBS }}
        application_name: warehouse-backend-test
        environment_name: Warehousebackendtest-env
        use_existing_version_if_available: false
        version_label: 12345
        region: sa-east-1
        deployment_package: script.zip
        


